version: '3'
services:
  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
  drone-server:
    image: drone/drone:1
    restart: always
    ports:
      - 8980:80
    volumes:
      - './drone-server/data:/data'
    environment:
      DRONE_GITLAB_SERVER: gitlab-web:8929
      DRONE_GITLAB_CLIENT_ID: ${DRONE_GITLAB_CLIENT_ID}
      DRONE_GITLAB_CLIENT_SECRET: ${DRONE_GITLAB_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
    extra_hosts:
      - 'drone.local.com:<host ip>'
  #drone-runner:
    #image: drone/drone-runner-docker:1
